apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-ingress
  namespace: travel-booking
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: travel.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: travel-api
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: travel-frontend
                port:
                  number: 3000
  tls:
    - hosts:
        - travel.example.com
      secretName: travel-tls
